controller_manager:
  ros__parameters:
    update_rate: 50 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - ur_1/shoulder_pan_joint
      - ur_1/shoulder_lift_joint
      - ur_1/elbow_joint
      - ur_1/wrist_1_joint
      - ur_1/wrist_2_joint
      - ur_1/wrist_3_joint
      - ur_2/shoulder_pan_joint
      - ur_2/shoulder_lift_joint
      - ur_2/elbow_joint
      - ur_2/wrist_1_joint
      - ur_2/wrist_2_joint
      - ur_2/wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
